### PR TITLE
Undo Behaviour

### PR DESCRIPTION
**Pull request by aaronvark**
Implemented support for Undo behaviour for the following actions:
- Create
- Delete
- Connect
- Disconnect

Deletions that involve disconnections & paste actions store these are separate undo actions (for now)

Needs a bit of stability testing... Redo functionality has been commented out for now since there were some issues with the UndoData getting corrupted after repeat undo/redo loops (probably some pointers being lost).

### CODE REVIEW

**Comment by sphaero** [comment]
Merge? or wait for more testing?

**Comment by sphaero** [comment]
btw, great addition

**Comment by aaronvark** [comment]
Going to test it some more tomorrow, then we can probably merge. I might need to fix a few little things.

**Comment by aaronvark** [comment]
Playing with the Redo option, after creating, then Undo->Redo->Undo->Redo, zsock_bind returns -1 when binding the actor's handle to its endpoint, and apparently this is caused by:
#define ZMQ_MAP_INSERT_OR_EMPLACE(k, v) emplace (k, v)

**Comment by sphaero** [comment]
This is probably because a socket is created, deleted, and then re-created. However socket creation probably is a system call which means the OS has not cleaned up yet when it is recreated. Not sure what to do with that....

**Comment by aaronvark** [comment]
Should be stable enough to merge. Undo/Redo now works as expected.

**Pull request merged**
